import streamlit as st
import pandas as pd
import plotly.express as px

from utils.engine_runner import run_strategy_engine


def show():
    st.title("📈 Monte Carlo Analysis")
    st.write("""This page analyses the distribution of simulated race outcomes generated by the Monte Carlo engine.""")
    st.divider()

    with st.spinner("Running simulations..."):
        engine = run_strategy_engine()

    best_strategy = engine["best_strategy"]
    results = engine["results"]


    best_result = None

    for strategy, result in results:
        if strategy == best_strategy:
            best_result = result
            break

    if best_result is None:
        st.error("Simulation results could not be loaded.")
        return

    race_times = best_result["race_times"]
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric("Average", f"{best_result['average_time']:.2f}s")

    with col2:
        st.metric("Best", f"{best_result['best_time']:.2f}s")

    with col3:
        st.metric("Worst", f"{best_result['worst_time']:.2f}s")

    with col4:
        st.metric("Variation", f"{best_result['variation']:.3f}")

    with col5:
        st.metric("Consistency", f"{best_result['consistency_score']:.4f}")

    st.divider()

    st.subheader("Race Time Distribution")
    df = pd.DataFrame({"Race Time (s)": race_times})
    histogram = px.histogram(df, x="Race Time (s)", nbins=30, title="Distribution of Simulated Race Times")
    histogram.update_layout(xaxis_title="Race Time (seconds)", yaxis_title="Frequency")
    st.plotly_chart(histogram, use_container_width=True)
    st.divider()

    st.subheader("Race Time Spread")
    box = px.box(df, y="Race Time (s)", title="Monte Carlo Race Time Spread")
    st.plotly_chart(box, use_container_width=True)
    st.divider()

    st.subheader("Simulation Summary")
    st.dataframe(df.describe(), use_container_width=True)