import streamlit as st

from utils.engine_runner import run_strategy_engine

def show():
    st.title("Strategy Optimiser")
    st.write("""This page displays the optimal race strategy generated by the probabilistic optimisation engine.
    Strategies are evaluated using Monte Carlo simulation, considering tyre degradation, race uncertainty, and performance variation. """)
    st.divider()

    with st.spinner("Running strategy optimisation..."):
        engine = run_strategy_engine(st.session_state["race_name"], st.session_state["years"], st.session_state["driver_code"])

    best_strategy = engine["best_strategy"]
    results = engine["results"]



    best_result = None
    for strategy, result in results:
        if strategy == best_strategy:
            best_result = result
            break


    if best_result is None:
        st.error("Unable to find evaluation results for the best strategy.")
        return


    st.subheader("Recommended Strategy")
    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Starting Compound",best_strategy.starting_compound)

    with col2:
        st.metric("Pit Stops",len(best_strategy.pit_stops))

    with col3:

        pit_laps = ", ".join(str(pit.lap) for pit in best_strategy.pit_stops)
        st.metric("Pit Laps",pit_laps)

    st.divider()

    st.subheader("Simulation Performance")
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Average Race Time",f"{best_result['average_time']:.2f}s")

    with col2:
        st.metric("Best Case",f"{best_result['best_time']:.2f}s")

    with col3:
        st.metric("Variation",f"{best_result['variation']:.4f}")

    with col4:
        st.metric("Consistency Score",f"{best_result['consistency_score']:.4f}")

    st.divider()

    st.subheader("Strategy Comparison")
    comparison_data = []

    for strategy, result in results:
        compounds = strategy.starting_compound

        for pit in strategy.pit_stops:
            compounds += f" → {pit.new_compound}"


        pit_laps = ", ".join(str(pit.lap) for pit in strategy.pit_stops)
        comparison_data.append({"Strategy": compounds,
                "Pit Laps": pit_laps,
                "Average Time": round(result["average_time"], 2),
                "Risk": round(result["variation"], 4),
                "Consistency": round(result["consistency_score"], 4)})

    st.dataframe(comparison_data, use_container_width=True)
    st.divider()

    st.subheader("Strategy Interpretation")
    st.write("""The selected strategy represents the best balance between expected race performance and consistency across Monte Carlo simulations.
        Unlike a deterministic model, the optimiser evaluates multiple possible race outcomes and accounts for uncertainty in tyre performance and race conditions.""")