from src.models.weather import Weather


# monte carlo
DEFAULT_SIMULATIONS = 1000


# pit stops
PIT_STOP_MEAN = 22.5
PIT_STOP_STD = 1.2


# traffic
TRAFFIC_PROBABILITY = 0.20
LIGHT_TRAFFIC_MIN = 0.2
LIGHT_TRAFFIC_MAX = 0.6
HEAVY_TRAFFIC_MIN = 0.7
HEAVY_TRAFFIC_MAX = 1.5


# safety car
SAFETY_CAR_PROBABILITY = 0.25
SAFETY_CAR_MIN_LAP = 10
SAFETY_CAR_MAX_LAP = 45
SAFETY_CAR_MIN_DURATION = 2
SAFETY_CAR_MAX_DURATION = 4
SAFETY_CAR_TIME_LOSS = 5.0


# weather
INITIAL_WEATHER_PROBABILITIES = {Weather.DRY: 0.70,
    Weather.LIGHT_RAIN: 0.25,
    Weather.HEAVY_RAIN: 0.05,}

WEATHER_CHANGE_PROBABILITY = 0.10


# randomness
LAP_TIME_RANDOMNESS_MULTIPLIER = 1.5