from src.models.weather import Weather

# monte carlo
DEFAULT_SIMULATIONS = 1000


# pit stops
PIT_STOP_STD = 1.2

# traffic
LIGHT_TRAFFIC = 0.20
HEAVY_TRAFFIC = 0.28

# safety car
SAFETY_CAR_PROBABILITY = 0.25
SAFETY_CAR_MIN_LAP = 10
SAFETY_CAR_MAX_LAP = 45
SAFETY_CAR_TIME_LOSS = 5.0

# weather
INITIAL_WEATHER_PROBABILITIES = {Weather.DRY: 0.70, Weather.LIGHT_RAIN: 0.25, Weather.HEAVY_RAIN: 0.05,}
WEATHER_CHANGE_PROBABILITY = 0.10

# randomness
LAP_TIME_RANDOMNESS_MULTIPLIER = 1.5

# strategy optimisation settings
FAST_OPTIMISATION_SIMULATIONS = 200
FINAL_OPTIMISATION_SIMULATIONS = 1000
TOP_STRATEGIES_TO_VALIDATE = 10

